#!/usr/bin/env python3
"""
Epic Generator - Epicテンプレートからの自動生成

機能:
- 設定ファイルからEpicドキュメント生成
- テンプレートベースの構造化出力
- charter.yml形式への変換

使用例:
    python epic_generator.py --config config.yaml --output epic.md
"""

import argparse
import yaml
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, Optional
from string import Template


class EpicGenerator:
    """Epic生成クラス"""

    EPIC_TEMPLATE = """# Epic: ${title}

## 背景（Background）

${background}

## 目的（Objective）

${objective}

## ビジネス価値（Business Value）

- 対象ユーザー: ${target_users}
- 期待成果: ${expected_outcome}
- 測定可能KPI:
${kpi_list}

## スコープ（Scope）

### In Scope（含む範囲）
${in_scope_list}

### Out of Scope（含まない範囲）
${out_of_scope_list}

## 前提条件と制約（Assumptions & Constraints）

### 技術的前提
${technical_constraints}

### リソース制約
${resource_constraints}

### 期間制約
${timeline_constraints}

## 成功指標（Success Metrics）

| 指標 | 目標値 | 現在値 |
|------|--------|--------|
${metrics_table}

## ステークホルダー（Stakeholders）

- **Epic Owner**: ${epic_owner}
- **Technical Lead**: ${technical_lead}
- **関連チーム**: ${related_teams}

## 受け入れ条件（Acceptance Criteria）

Epicの完了を判定するための客観的条件:

${acceptance_criteria}

---

*生成日時: ${generated_at}*
*設定ファイル: ${config_file}*
"""

    CHARTER_TEMPLATE = """# Charter - ${project_name}
# Generated by Epic-Driven Planning Tools
# ${generated_at}

goal: |
  ${goal}

non_goals:
${non_goals}

success_metrics:
${success_metrics}

milestones: []  # epic_decomposer.py で生成

stakeholders:
  epic_owner: "${epic_owner}"
  technical_lead: "${technical_lead}"
"""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.project = config.get('project', {})
        self.epic = config.get('epic', {})
        self.stakeholders = config.get('stakeholders', {})

    def generate(self) -> Dict[str, Any]:
        """Epic生成のメイン処理"""
        epic_md = self._generate_epic_markdown()
        charter_yml = self._generate_charter_yaml()

        return {
            'epic_markdown': epic_md,
            'charter_yaml': charter_yml,
            'title': self._extract_title(),
            'features_count': 0,  # decomposerで更新
        }

    def _extract_title(self) -> str:
        """Epicタイトルを抽出"""
        goal = self.epic.get('goal', '')
        # 最初の行または最初の50文字をタイトルとして使用
        lines = goal.strip().split('\n')
        title = lines[0] if lines else 'Untitled Epic'
        return title[:80] if len(title) > 80 else title

    def _generate_epic_markdown(self) -> str:
        """Epic Markdownを生成"""
        template = Template(self.EPIC_TEMPLATE)

        # KPIリスト生成
        kpi_list = ""
        for metric in self.epic.get('success_metrics', []):
            kpi_list += f"  - {metric.get('metric', 'N/A')}: {metric.get('target', 'N/A')}\n"

        # スコープリスト生成
        scope = self.epic.get('scope', {})
        in_scope_list = "\n".join([f"- {item}" for item in scope.get('in_scope', ['未定義'])])
        out_of_scope_list = "\n".join([f"- {item}" for item in scope.get('out_of_scope', ['未定義'])])

        # 制約リスト生成
        constraints = self.epic.get('constraints', {})
        technical = "\n".join([f"- {item}" for item in constraints.get('technical', ['未定義'])])
        resource = "\n".join([f"- {item}" for item in constraints.get('resource', ['未定義'])])
        timeline = "\n".join([f"- {item}" for item in constraints.get('timeline', ['未定義'])])

        # メトリクステーブル生成
        metrics_table = ""
        for metric in self.epic.get('success_metrics', []):
            metrics_table += f"| {metric.get('metric', 'N/A')} | {metric.get('target', 'N/A')} | {metric.get('current', '-')} |\n"

        # 受け入れ条件生成（デフォルト）
        acceptance_criteria = self._generate_default_acceptance_criteria()

        return template.safe_substitute(
            title=self._extract_title(),
            background=self.epic.get('background', '背景未定義'),
            objective=self.epic.get('goal', '目的未定義'),
            target_users=self.stakeholders.get('target_users', '未定義'),
            expected_outcome=self.epic.get('expected_outcome', '未定義'),
            kpi_list=kpi_list or "  - 未定義",
            in_scope_list=in_scope_list,
            out_of_scope_list=out_of_scope_list,
            technical_constraints=technical,
            resource_constraints=resource,
            timeline_constraints=timeline,
            metrics_table=metrics_table or "| 未定義 | - | - |",
            epic_owner=self.stakeholders.get('epic_owner', '未割り当て'),
            technical_lead=self.stakeholders.get('technical_lead', '未割り当て'),
            related_teams=", ".join(self.stakeholders.get('related_teams', ['未定義'])),
            acceptance_criteria=acceptance_criteria,
            generated_at=datetime.now().isoformat(),
            config_file=str(self.config.get('_config_path', 'N/A'))
        )

    def _generate_default_acceptance_criteria(self) -> str:
        """デフォルトの受け入れ条件を生成"""
        criteria = []

        # 成功指標から条件を生成
        for metric in self.epic.get('success_metrics', []):
            criteria.append(f"- [ ] {metric.get('metric', 'KPI')}: {metric.get('target', '目標値')}を達成")

        # スコープから条件を生成
        for item in self.epic.get('scope', {}).get('in_scope', [])[:3]:
            criteria.append(f"- [ ] {item}が実装・検証完了")

        # 基本条件を追加
        criteria.extend([
            "- [ ] テストカバレッジ80%以上",
            "- [ ] ドキュメント更新完了",
            "- [ ] ステークホルダーレビュー完了"
        ])

        return "\n".join(criteria[:7])  # 最大7個

    def _generate_charter_yaml(self) -> str:
        """charter.yaml形式を生成"""
        template = Template(self.CHARTER_TEMPLATE)

        # non_goals生成
        non_goals = ""
        for item in self.epic.get('scope', {}).get('out_of_scope', []):
            non_goals += f"  - \"{item}\"\n"

        # success_metrics生成
        success_metrics = ""
        for metric in self.epic.get('success_metrics', []):
            success_metrics += f"""  - metric: "{metric.get('metric', 'N/A')}"
    target: "{metric.get('target', 'N/A')}"
    current: "{metric.get('current', '-')}"
"""

        return template.safe_substitute(
            project_name=self.project.get('name', 'unnamed'),
            generated_at=datetime.now().isoformat(),
            goal=self.epic.get('goal', '').strip(),
            non_goals=non_goals or "  - \"未定義\"",
            success_metrics=success_metrics or "  []",
            epic_owner=self.stakeholders.get('epic_owner', '未割り当て'),
            technical_lead=self.stakeholders.get('technical_lead', '未割り当て'),
        )

    def save_outputs(self, output_dir: Path):
        """出力ファイルを保存"""
        output_dir.mkdir(parents=True, exist_ok=True)

        result = self.generate()

        # Epic Markdown保存
        epic_path = output_dir / "epic.md"
        epic_path.write_text(result['epic_markdown'], encoding='utf-8')
        print(f"✅ Epic Markdown: {epic_path}")

        # Charter YAML保存
        charter_path = output_dir / "charter.yml"
        charter_path.write_text(result['charter_yaml'], encoding='utf-8')
        print(f"✅ Charter YAML: {charter_path}")

        return result


def main():
    parser = argparse.ArgumentParser(description="Epic生成ツール")
    parser.add_argument('--config', '-c', required=True, help='設定ファイルパス')
    parser.add_argument('--output', '-o', default='.concept', help='出力ディレクトリ')
    parser.add_argument('--dry-run', '-n', action='store_true', help='プレビューのみ')

    args = parser.parse_args()

    # 設定読み込み
    with open(args.config, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)
    config['_config_path'] = args.config

    generator = EpicGenerator(config)

    if args.dry_run:
        result = generator.generate()
        print("=== Epic Markdown ===")
        print(result['epic_markdown'][:500] + "...")
        print("\n=== Charter YAML ===")
        print(result['charter_yaml'])
    else:
        generator.save_outputs(Path(args.output))


if __name__ == "__main__":
    main()
